input {
  file {
    path => "/data/logs/zeek/current/dns.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  if [message] =~ /^#/ { drop { } }

  dissect {
    mapping => {
      "message" => "%{ts}	%{uid}	%{id.orig_h}	%{id.orig_p}	%{id.resp_h}	%{id.resp_p}	%{proto}	%{trans_id}	%{rtt}	%{query}	%{qclass}	%{qclass_name}	%{qtype}	%{qtype_name}	%{rcode}	%{rcode_name}	%{AA}	%{TC}	%{RD}	%{RA}	%{Z}	%{answers}	%{TTLs}	%{rejected}"
    }
  }

  date {
    match => ["ts", "UNIX"]
    target => "@timestamp"
  }

  mutate {
    rename => {
      "id.orig_h" => "src_ip"
      "id.resp_h" => "dns_server"
      "query" => "dns_query"
      "answers" => "dns_answers"
    }
    add_field => {
      "log_type" => "zeek"
      "event_type" => "dns"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "zeek-dns-%{+YYYY.MM.dd}"
  }
}
