input {
  file {
    path => "/data/logs/zeek/current/http.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  if [message] =~ /^#/ { drop { } }

  dissect {
    mapping => {
      "message" => "%{ts}	%{uid}	%{id.orig_h}	%{id.orig_p}	%{id.resp_h}	%{id.resp_p}	%{trans_depth}	%{method}	%{host}	%{uri}	%{referrer}	%{version}	%{user_agent}	%{origin}	%{request_body_len}	%{response_body_len}	%{status_code}	%{status_msg}	%{info_code}	%{info_msg}	%{tags}	%{username}	%{password}	%{proxied}	%{orig_fuids}	%{orig_filenames}	%{orig_mime_types}	%{resp_fuids}	%{resp_filenames}	%{resp_mime_types}"
    }
  }

  date {
    match => ["ts", "UNIX"]
    target => "@timestamp"
  }

  mutate {
    convert => {
      "status_code" => "integer"
      "request_body_len" => "integer"
      "response_body_len" => "integer"
    }
    rename => {
      "id.orig_h" => "src_ip"
      "id.resp_h" => "dst_ip"
    }
    add_field => {
      "log_type" => "zeek"
      "event_type" => "http"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "zeek-http-%{+YYYY.MM.dd}"
  }
}
