input {
  file {
    path => "/data/logs/zeek/current/notice.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  if [message] =~ /^#/ { drop { } }

  dissect {
    mapping => {
      "message" => "%{ts}	%{uid}	%{id.orig_h}	%{id.orig_p}	%{id.resp_h}	%{id.resp_p}	%{fuid}	%{file_mime_type}	%{file_desc}	%{proto}	%{note}	%{msg}	%{sub}	%{src}	%{dst}	%{p}	%{n}	%{peer_descr}	%{actions}	%{suppress_for}	%{remote_location.country_code}	%{remote_location.region}	%{remote_location.city}	%{remote_location.latitude}	%{remote_location.longitude}"
    }
  }

  date {
    match => ["ts", "UNIX"]
    target => "@timestamp"
  }

  mutate {
    rename => {
      "id.orig_h" => "src_ip"
      "id.resp_h" => "dst_ip"
      "note" => "alert_type"
      "msg" => "alert_message"
    }
    add_field => {
      "log_type" => "zeek"
      "event_type" => "alert"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "zeek-alerts-%{+YYYY.MM.dd}"
  }
}
