# path.config: /usr/share/logstash/pipeline  # Commenté pour utiliser pipelines.yml
path.logs: /var/log/logstash
# pipeline.workers et pipeline.batch.size sont maintenant définis par pipeline dans pipelines.yml
# pipeline.workers: 2
# pipeline.batch.size: 125
pipeline.batch.delay: 50
queue.type: memory
